### ISSUE TITLE
constraint expressions and compiler version (may not be an issue)

### ISSUE THREAD

**Issue by pauldavisthefirst** [nucleic/kiwi#81]
Hi Kiwi folks. Working on using Kiwi in the context of Ardour (ardour.org). Have the following tiny blob of code:

```
#include "kiwi/kiwi.h"
int main (int, char* [])
{
	kiwi::Solver solver;
	kiwi::Variable v ("variable");

	solver.addConstraint (v >= 40, kiwi::strength::required);
        return 0;
}
```

which seems to be appropriate given the docs. Trying to compile this with gcc 8.3, and getting: 

```
kt.cc: In function ‘int main(int, char**)’:
kt.cc:9:57: error: no matching function for call to ‘kiwi::Solver::addConstraint(kiwi::Constraint, const double&)’
  solver.addConstraint (v >= 40, kiwi::strength::required);
                                                         ^
In file included from kiwi/kiwi.h:14,
                 from kt.cc:1:
kiwi/solver.h:39:7: note: candidate: ‘void kiwi::Solver::addConstraint(const kiwi::Constraint&)’
  void addConstraint( const Constraint& constraint )
       ^~~~~~~~~~~~~
kiwi/solver.h:39:7: note:   candidate expects 1 argument, 2 provided
```

It can be fixed by adding Constraint () around the expression in the call to Solver::addConstraint() but that feels ugly :)

Does anyone know what version of gcc (or flags) are required to compile this as written?

**Comment by sccolbert** [comment]
The c++ api is not exactly the same as the Python api. There is no 2 argument form of ::addConstraint.

**Comment by MatthieuDartiailh** [comment]
This is an error in the documentation (sorry for that I rarely use the c++ API directly), the correct syntax is:
```c++
#include "kiwi/kiwi.h"
int main (int, char* [])
{
	kiwi::Solver solver;
	kiwi::Variable v ("variable");

	solver.addConstraint (v >= 40 | kiwi::strength::required);
        return 0;
}
```
Once you confirm it works I will update the documentation.

**Comment by pauldavisthefirst** [comment]
use of the | operator confirmed working with gcc 8.3. thanks so much for the rapid response.

**Comment by MatthieuDartiailh** [comment]
No problem. I pushed the fix for the docs and will close the issue.
